#!/usr/local/bin/php
<?php
require __DIR__.'/vendor/autoload.php';

$boardLoader = new \BoardLoader\FileLoader();
$board = $boardLoader->load(__DIR__.'/board/planneur.board');

$game       = new \Game();
$screen     = new \Screen\ConsoleScreen();
$gameRunner = new \GameRunner\GameRunner($game, $screen);

$gameRunner->run($board, 8, true, false);