#!/usr/local/bin/php
<?php
require __DIR__.'/vendor/autoload.php';

$board = array(
    array(\Game::STATE_DEAD, \Game::STATE_LIFE, \Game::STATE_DEAD),
    array(\Game::STATE_DEAD, \Game::STATE_LIFE, \Game::STATE_DEAD),
    array(\Game::STATE_DEAD, \Game::STATE_LIFE, \Game::STATE_DEAD),
);

$game       = new \Game();
$screen     = new \Screen\ConsoleScreen();
$gameRunner = new GameRunner($game, $screen);

$gameRunner->run($board, 5);